%% title: 滴滴国际化客服质检智能化之路
graph TD
    A["滴滴国际化客服质检智能化之路：基于 Amazon Bedro"] ==> B["[亚马逊AWS官方博客]加https://aws.amazo"]
    B ==> C["**一、关于滴滴国际化事业部**"]
    C ==> D["**二、业务挑战**"]
    D ==> E["**三、方案总览**"]
    E ==> SUM["总结与实践启示"]
