services:
  wiki-book:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
      network: host
    container_name: wiki-book
    ports:
      - "8002:8080"
    restart: unless-stopped
