services:
  wiki-book:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
      args:
        http_proxy: ""
        https_proxy: ""
        HTTP_PROXY: ""
        HTTPS_PROXY: ""
    container_name: wiki-book
    ports:
      - "8002:8080"
    restart: unless-stopped
